package snitch

import (
	"errors"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

const DefaultRepository = "aljrico/Google-Play-Console-CLI"

var repositorySegmentPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9_.-]*$`)

type ReportOptions struct {
	Repository string   `json:"repository,omitempty"`
	Title      string   `json:"title"`
	Body       string   `json:"body,omitempty"`
	Command    string   `json:"command,omitempty"`
	Labels     []string `json:"labels,omitempty"`
}

type Report struct {
	Repository string   `json:"repository"`
	Title      string   `json:"title"`
	Body       string   `json:"body"`
	Command    string   `json:"command,omitempty"`
	Labels     []string `json:"labels,omitempty"`
	IssueURL   string   `json:"issueUrl"`
}

func BuildReport(options ReportOptions) (Report, error) {
	if err := options.Validate(); err != nil {
		return Report{}, err
	}
	repository := options.repository()
	body := reportBody(options)
	labels := normalizeLabels(options.Labels)
	issueURL, err := issueURL(repository, options.Title, body, labels)
	if err != nil {
		return Report{}, err
	}
	return Report{
		Repository: repository,
		Title:      options.Title,
		Body:       body,
		Command:    strings.TrimSpace(options.Command),
		Labels:     labels,
		IssueURL:   issueURL,
	}, nil
}

func (o ReportOptions) Validate() error {
	if strings.TrimSpace(o.Title) == "" {
		return fmt.Errorf("title is required")
	}
	if strings.TrimSpace(o.Title) != o.Title {
		return fmt.Errorf("title cannot have leading or trailing whitespace")
	}
	if strings.TrimSpace(o.Repository) != o.Repository {
		return fmt.Errorf("repository cannot have leading or trailing whitespace")
	}
	repository := o.repository()
	if err := validateRepository(repository); err != nil {
		return err
	}
	for _, label := range o.Labels {
		if err := validateLabel(label); err != nil {
			return err
		}
	}
	return nil
}

func validateRepository(repository string) error {
	parts := strings.Split(repository, "/")
	if len(parts) != 2 {
		return fmt.Errorf("repository must use owner/name")
	}
	for _, part := range parts {
		if part == "." || part == ".." || !repositorySegmentPattern.MatchString(part) {
			return fmt.Errorf("repository must use owner/name")
		}
	}
	return nil
}

func validateLabel(label string) error {
	label = strings.TrimSpace(label)
	if label == "" {
		return nil
	}
	if strings.Contains(label, ",") {
		return fmt.Errorf("label %q cannot contain commas", label)
	}
	for _, r := range label {
		if unicode.IsControl(r) {
			return errors.New("label cannot contain control characters")
		}
	}
	return nil
}

func (o ReportOptions) repository() string {
	if o.Repository == "" {
		return DefaultRepository
	}
	return o.Repository
}

func reportBody(options ReportOptions) string {
	sections := []string{}
	if strings.TrimSpace(options.Body) != "" {
		sections = append(sections, strings.TrimSpace(options.Body))
	}
	if strings.TrimSpace(options.Command) != "" {
		sections = append(sections, "Command:\n\n```sh\n"+strings.TrimSpace(options.Command)+"\n```")
	}
	if len(sections) == 0 {
		return "CLI friction report generated by `playpub snitch report`."
	}
	return strings.Join(sections, "\n\n")
}

func normalizeLabels(labels []string) []string {
	seen := map[string]bool{}
	normalized := make([]string, 0, len(labels)+1)
	for _, label := range append([]string{"snitch"}, labels...) {
		label = strings.TrimSpace(label)
		if label == "" || seen[label] {
			continue
		}
		seen[label] = true
		normalized = append(normalized, label)
	}
	sort.Strings(normalized)
	return normalized
}

func issueURL(repository string, title string, body string, labels []string) (string, error) {
	baseURL, err := url.Parse("https://github.com/" + repository + "/issues/new")
	if err != nil {
		return "", fmt.Errorf("build issue URL: %w", err)
	}
	values := url.Values{}
	values.Set("title", title)
	values.Set("body", body)
	if len(labels) > 0 {
		values.Set("labels", strings.Join(labels, ","))
	}
	baseURL.RawQuery = values.Encode()
	return baseURL.String(), nil
}
